// svelte-docs/src/xui/modal/Modal.svelte
<script lang="ts">
import './styles.css';
import { onMount, onDestroy } from 'svelte';
import type { Writable } from 'svelte/store';
import { writable } from 'svelte/store';

export let title: string = "";
export let isOpen: boolean = false;
export let onClose: () => void = () => {};
export let component: boolean = false;
export let isStatic: boolean = false;

const open: Writable<boolean> = writable(isOpen);

$: open.set(isOpen);

function handleKeyDown(event: KeyboardEvent) {
    if (event.key === "Escape" && !isStatic && component) close();
}

function close() {
    if (!isStatic) {
        open.set(false);
    }
    onClose?.();
}

function handleClickOutside(event: MouseEvent) {
    const backdrop = document.getElementById('modal-backdrop');
    if (event.target === backdrop && !isStatic && component) close();
}

onMount(() => {
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
    document.removeEventListener('keydown', handleKeyDown);
    document.removeEventListener('mousedown', handleClickOutside);
    };
});
</script>

<svelte:window on:keydown={handleKeyDown} />
<div 
    id="modal-backdrop" 
    class="modal-backdrop" 
    role="button"
    tabindex="0" 
    on:keydown={handleKeyDown}
    on:mousedown={handleClickOutside} 
    style:display={$open ? 'flex' : 'none'}>
>
{#if component}
    <div class="modal-content" >
        <div class="modal-title">{title}</div>
            <slot></slot>
        <div class="modal-footer">
            <button class="modal-button" on:click={close}>OK</button>
        </div>
    </div>
{:else}
    <slot></slot>
{/if}
</div>

// vue-docs/src/xui/Modal/Modal.vue
<template>
  <Teleport to="body" v-if="open">
    <div
      id="modal-backdrop"
      class="modal-backdrop"
      @mousedown="handleClickOutside"
    >
      <div v-if="component" class="modal-content" @click.stop>
        <div class="modal-title">{{ title }}</div>
        <slot></slot>
        <div class="modal-footer">
          <button class="modal-button" @click="close">OK</button>
        </div>
      </div>
      <template v-else>
        <slot></slot>
      </template>
    </div>
  </Teleport>
</template>

<script setup>
import { ref, watch, onMounted, onUnmounted } from "vue";

const props = defineProps({
  title: String,
  isOpen: Boolean,
  onClose: Function,
  component: Boolean,
  isStatic: Boolean,
});
const open = ref(props.isOpen ?? false);

watch(
  () => props.isOpen,
  (newValue) => {
    if (newValue !== undefined) open.value = newValue;
  }
);

const close = () => {
  if (!props.isStatic) {
    open.value = false;
  }
  props.onClose?.();
};

const handleKeyDown = (event) => {
  if (event.key === "Escape" && !props.isStatic && props.component) close(); // ESC key
};

const handleClickOutside = (event) => {
  if (
    event.target.id === "modal-backdrop" &&
    !props.isStatic &&
    props.component
  )
    close();
};

onMounted(() => {
  document.addEventListener("keydown", handleKeyDown);
});
onUnmounted(() => {
  document.removeEventListener("keydown", handleKeyDown);
  document.removeEventListener("mousedown", handleClickOutside);
});
</script>

<style scoped>
@import "./styles.css";
</style>
