// libs/x-ui-components-svelte/src/select/Select.svelte
<script lang="ts">
import './styles.css'
import { onMount, onDestroy } from 'svelte';
import type { Option } from './types'

export let options: Option[] = [];
export let defaultValue: string | number | undefined = undefined;
export let valueProp: Option | undefined = undefined;
export let open: boolean | undefined = false;
export let disabled: boolean = false;
export let onChange: (value: Option) => void = (v) => {};
export let onInputClick: () => void = () => {};
export let component: boolean = false;
export let isStatic: boolean = false;

let value: Option | undefined = options?.find(option => option.id === defaultValue);
let areOptionsVisible = open;
let dropdownRef: HTMLDivElement;

$: if (open !== undefined) {
    areOptionsVisible = open;
}

$: if (valueProp !== undefined) {
    value = valueProp;
}

function toggleDropdownVisibility() {
    if (!isStatic) {
        areOptionsVisible = !areOptionsVisible;
    }
    onInputClick?.();
}

function selectOption(option: Option) {
    if (!isStatic) {
        value = option;
        areOptionsVisible = false;
    }
    onChange?.(option);
}

function handleClickOutside(event: MouseEvent) {
    if (!isStatic && dropdownRef && !dropdownRef.contains(event.target as Node)) {
        areOptionsVisible = false;
    }
}

function handleKeyDown(event: KeyboardEvent) {
    if (!isStatic && event.key === 'Escape') {
        areOptionsVisible = false;
    }
}

onMount(() => {
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
        document.removeEventListener('mousedown', handleClickOutside);
        document.removeEventListener('keydown', handleKeyDown);
    };
});
</script>

<div class="select-wrapper">
{#if component}
    <div class="select-input-wrapper">
        <input
            class="select-input"
            type="text"
            value={value?.value ?? ""}
            on:click={toggleDropdownVisibility}
            disabled={disabled}
            readonly
        />
        {#if areOptionsVisible}
            <div bind:this={dropdownRef} class="select-dropdown">
                {#each options as option}
                    <div
                        class="select-option {option.id === value?.id ? 'selected' : ''}"
                        on:click={() => selectOption(option)}
                        on:keydown={event => event.key === 'Enter' || event.key === 'Space' && selectOption(option)}
                        tabindex="0"
                        role="button"
                    >
                        {option.value}
                    </div>
                {/each}
            </div>
        {/if}
    </div>
{:else}
    <slot></slot>
{/if}
</div>

// libs/x-ui-components-vue/src/Select/Select.vue
<script setup>
import { ref, watch, onMounted, onUnmounted, reactive, computed } from "vue";

const props = defineProps({
  options: Array,
  defaultValue: Object,
  value: Object,
  open: Boolean,
  disabled: Boolean,
  onChange: Function,
  onInputClick: Function,
  component: Boolean,
  isStatic: Boolean,
});

const initialValue = props.options?.find(
  (option) => option.id === props.defaultValue
);
const inputValue = ref(initialValue);
const areOptionsVisible = ref(props.open ?? false);
const dropdownRef = ref(null);

watch(
  () => props.open,
  (newOpen) => {
    if (newOpen !== undefined) areOptionsVisible.value = newOpen;
  }
);

watch(
  () => props.value,
  (newValue) => {
    if (newValue !== undefined) inputValue.value = newValue;
  }
);

const handleInputClick = () => {
  if (!props.isStatic) {
    areOptionsVisible.value = !areOptionsVisible.value;
  }
  props.onInputClick?.();
};

const handleOptionClick = (option) => {
  if (!props.isStatic) {
    inputValue.value = option;
    areOptionsVisible.value = false;
  }
  props.onChange?.(option);
};

const handleClickOutside = (event) => {
  if (
    !props.isStatic &&
    dropdownRef.value &&
    !dropdownRef.value.contains(event.target)
  ) {
    areOptionsVisible.value = false;
  }
};

const handleKeyDown = (event) => {
  if (!props.isStatic && event.key === "Escape") {
    areOptionsVisible.value = false;
  }
};

onMounted(() => {
  document.addEventListener("mousedown", handleClickOutside);
  document.addEventListener("keydown", handleKeyDown);
});

onUnmounted(() => {
  document.removeEventListener("mousedown", handleClickOutside);
  document.removeEventListener("keydown", handleKeyDown);
});

const displayValue = computed(() => inputValue.value?.value ?? "");
</script>

<template>
  <div class="select-wrapper">
    <div v-if="component">
      <div class="select-input-wrapper">
        <input
          class="select-input"
          type="text"
          :value="displayValue"
          @click="handleInputClick"
          :disabled="disabled"
          readonly
        />
      </div>
      <div v-show="areOptionsVisible" ref="dropdownRef" class="select-dropdown">
        <div
          v-for="option in options"
          :key="option.id"
          :class="['select-option', { selected: inputValue?.id === option.id }]"
          @click="handleOptionClick(option)"
        >
          {{ option.value }}
        </div>
      </div>
    </div>
    <template v-else>
      <slot></slot>
    </template>
  </div>
</template>

<style scoped>
@import "./styles.css";
</style>
