// vue-docs/src/xui/Accordion/Accordion.vue
<script setup>
import { ref, watch, defineProps } from "vue";

const props = defineProps({
  expanded: Boolean,
  title: String,
  component: Boolean,
  isStatic: Boolean,
  onTitleClick: Function,
});

const expanded = ref(props.expanded ?? false);

watch(
  () => props.expanded,
  (newVal) => {
    if (newVal !== undefined) {
      expanded.value = newVal;
    }
  }
);

const handleClick = () => {
  if (!props.isStatic) {
    expanded.value = !expanded.value;
  }
  props.onTitleClick?.();
};
</script>

<template>
  <div class="accordion-wrapper">
    <template v-if="component">
      <button class="btn-accordion" @click="handleClick">
        <template v-if="expanded">
          <font-awesome-icon class="accordion-icon" icon="angle-up" />
        </template>
        <template v-else>
          <font-awesome-icon class="accordion-icon" icon="angle-down" />
        </template>
        {{ title }}
      </button>
      <div v-show="expanded">
        <slot></slot>
      </div>
    </template>
    <template v-else>
      <slot></slot>
    </template>
  </div>
</template>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components-react/src/Accordion/Accordion.tsx
import React, { useEffect, useState } from "react";
import "./styles.css";
import { FaAngleUp, FaAngleDown } from "react-icons/fa";

export interface ReactChildren {
  children: React.ReactNode;
}
export interface AccordionProps extends ReactChildren {
  expanded?: boolean;
  title?: string;
  component?: boolean;
  isStatic?: boolean;
  onTitleClick?: () => void;
}
export interface AccordionButtonProps extends ReactChildren {
  onClick: () => void;
}
export interface AccordionContentProps extends ReactChildren {
  visible: boolean;
}

Accordion.Button = ({
  onClick: btnOnClick,
  children,
  ...props
}: AccordionButtonProps) => {
  return (
    <button className="btn-accordion" onClick={btnOnClick} {...props}>
      {children}
    </button>
  );
};
Accordion.Content = ({
  visible,
  children,
  ...props
}: AccordionContentProps) => {
  return (
    <div className={`accordion-content ${visible ? "open" : ""}`} {...props}>
      {children}
    </div>
  );
};

export function Accordion({
  expanded: expandedProp,
  title,
  children,
  component,
  isStatic,
  onTitleClick,
  ...props
}: AccordionProps) {
  const [expanded, setExpanded] = useState(expandedProp ?? false);

  useEffect(() => {
    expandedProp !== undefined && setExpanded(expandedProp);
  }, [expandedProp]);

  if (component) {
    return (
      <div className="accordion-wrapper" {...props}>
        <button
          className="btn-accordion"
          onClick={() => {
            !isStatic && setExpanded(!expanded);
            onTitleClick?.();
          }}
        >
          {!expanded ? (
            <FaAngleDown className="accordion-icon" />
          ) : (
            <FaAngleUp className="accordion-icon" />
          )}
          {title}
        </button>
        <Accordion.Content visible={expanded}>{children}</Accordion.Content>
      </div>
    );
  }

  return <div className="accordion-wrapper">{children}</div>;
}
