// svelte-docs/src/xui/select/Select.svelte
<script lang="ts">
import './styles.css'
import { onMount, onDestroy } from 'svelte';
import type { Option } from './types'

export let options: Option[] = [];
export let defaultValue: string | number | undefined = undefined;
export let valueProp: Option | undefined = undefined;
export let open: boolean | undefined = false;
export let disabled: boolean = false;
export let onChange: (value: Option) => void = (v) => {};
export let onInputClick: () => void = () => {};
export let component: boolean = false;
export let isStatic: boolean = false;

let value: Option | undefined = options?.find(option => option.id === defaultValue);
let areOptionsVisible = open;
let dropdownRef: HTMLDivElement;

$: if (open !== undefined) {
    areOptionsVisible = open;
}

$: if (valueProp !== undefined) {
    value = valueProp;
}

function toggleDropdownVisibility() {
    if (!isStatic) {
    areOptionsVisible = !areOptionsVisible;
    onInputClick?.();
    }
}

function selectOption(option: Option) {
    if (!isStatic) {
    value = option;
    areOptionsVisible = false;
    onChange?.(option);
    }
}

function handleClickOutside(event: MouseEvent) {
    if (!isStatic && dropdownRef && !dropdownRef.contains(event.target as Node)) {
    areOptionsVisible = false;
    }
}

function handleKeyDown(event: KeyboardEvent) {
    if (!isStatic && event.key === 'Escape') {
    areOptionsVisible = false;
    }
}

onMount(() => {
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
    document.removeEventListener('mousedown', handleClickOutside);
    document.removeEventListener('keydown', handleKeyDown);
    };
});
</script>

<div class="select-wrapper">
{#if component}
    <div class="select-input-wrapper">
    <input
        class="select-input"
        type="text"
        value={value?.value ?? ""}
        on:click={toggleDropdownVisibility}
        disabled={disabled}
    />
    {#if areOptionsVisible}
        <div bind:this={dropdownRef} class="select-dropdown">
        {#each options as option}
            <div
            class="select-option {option.id === value?.id ? 'selected' : ''}"
            on:click={() => selectOption(option)}
            on:keydown={event => event.key === 'Enter' || event.key === 'Space' && selectOption(option)}
            tabindex="0"
            role="button"
            >
            {option.value}
            </div>
        {/each}
        </div>
    {/if}
    </div>
{:else}
    <slot></slot>
{/if}
</div>

// react-docs/src/xui/Select/Select.tsx
import { useEffect, useRef, useState } from "react";
import "./styles.css";

export interface ReactChildren {
  children?: React.ReactNode;
}

export interface Option {
  id: string | number;
  value: string;
}

export interface OptionsProps extends ReactChildren {
  options?: Option[];
  open?: boolean;
  disabled?: boolean;
  value?: Option;
  defaultValue?: string | number;
  onChange?: (value: Option) => void;
  onInputClick?: () => void;
  component?: boolean;
  isStatic?: boolean;
}

export interface SelectInputProps {
  onClick: () => void;
  value: Option;
  disabled?: boolean;
}

export interface SelectDropdownProps extends ReactChildren {
  visible: boolean;
}

export interface SelectOptionProps extends ReactChildren {
  onClick: () => void;
  selected?: boolean;
}

Select.Input = ({ value, onClick, disabled }: SelectInputProps) => {
  return (
    <div className="select-input-wrapper">
      <input
        className="select-input"
        type="text"
        value={value?.value ?? ""}
        onChange={() => {}}
        onClick={onClick}
        disabled={disabled}
      />
    </div>
  );
};

Select.Dropdown = ({ children, visible }: SelectDropdownProps) => {
  if (!visible) return <></>;
  return <div className="select-dropdown">{children}</div>;
};

Select.Option = ({
  onClick,
  children,
  selected,
  ...props
}: SelectOptionProps) => {
  return (
    <option
      className={`select-option ${Boolean(selected) ? "selected" : ""}`}
      onClick={onClick}
      {...props}
    >
      {children}
    </option>
  );
};

export function Select({
  options,
  defaultValue,
  value: valueProp,
  open,
  disabled,
  onChange,
  onInputClick,
  component,
  children,
  isStatic,
}: OptionsProps) {
  const initialValue = options?.find((option) => option.id === defaultValue);
  const [value, setValue] = useState<Option | undefined>(initialValue);
  const [areOptionsVisible, setAreOptionsVisible] = useState(open ?? false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    open !== undefined && setAreOptionsVisible(open);
  }, [open]);

  useEffect(() => {
    valueProp !== undefined && setValue(valueProp);
  }, [valueProp]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        !isStatic &&
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setAreOptionsVisible(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (!isStatic && event.keyCode === 27) setAreOptionsVisible(false); // ESC key
    };

    // Add when the component mounts
    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleKeyDown);

    // Return function to be called when unmounted
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  return (
    <div className="select-wrapper">
      {component ? (
        <>
          <div className="select-input-wrapper">
            <input
              className="select-input"
              type="text"
              value={value?.value ?? ""}
              onChange={() => {}}
              onClick={() => {
                !isStatic && setAreOptionsVisible(!areOptionsVisible);
                onInputClick?.();
              }}
              disabled={Boolean(disabled)}
            />
          </div>
          {areOptionsVisible && (
            <div ref={dropdownRef} className="select-dropdown">
              {options?.map((option) => (
                <option
                  key={option.id}
                  className={`select-option ${
                    value?.id === option.id ? "selected" : ""
                  }`}
                  onClick={() => {
                    !isStatic && setValue(option);
                    !isStatic && setAreOptionsVisible(false);
                    onChange?.(option);
                  }}
                >
                  {option.value}
                </option>
              ))}
            </div>
          )}
        </>
      ) : (
        children
      )}
    </div>
  );
}
