// vue-docs/src/components/Sidebar.vue
<script setup lang="ts">
import { ref } from "vue";

const activeItem = ref("overview");

function setActiveItem(item: string) {
  // Access/mutate the value of a ref via
  // its .value property.
  activeItem.value = item;
}
</script>

<template>
  <div className="sidebar">
    <div className="sidebar-content">
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'overview' }"
        @click="setActiveItem('overview')"
      >
        Overview
      </p>
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'menu' }"
        @click="setActiveItem('menu')"
      >
        Menu
      </p>
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'select' }"
        @click="setActiveItem('select')"
      >
        Select
      </p>
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'accordion' }"
        @click="setActiveItem('accordion')"
      >
        Accordion
      </p>
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'modal' }"
        @click="setActiveItem('modal')"
      >
        Modal
      </p>
      <p
        class="sidebar-item"
        :class="{ 'sidebar-item-active': activeItem === 'multiselect' }"
        @click="setActiveItem('multiselect')"
      >
        Multiselect
      </p>
    </div>
  </div>
</template>

// react-docs/src/components/Sidebar.tsx
import { useState } from "react";

enum ItemsEnum {
  Overview,
  Menu,
  Select,
  Accordion,
  Modal,
  Multiselect
}

export const Sidebar = () => {
  const [activeItem, setActiveItem] = useState<ItemsEnum>(ItemsEnum.Overview);

  return (
    <div className="sidebar">
      <div className="sidebar-content">
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Overview && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Overview)}
        >
          Overview
        </p>
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Menu && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Menu)}
        >
          Menu
        </p>
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Select && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Select)}
        >
          Select
        </p>
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Accordion && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Accordion)}
        >
          Accordion
        </p>
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Modal && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Modal)}
        >
          Modal
        </p>
        <p
          className={`sidebar-item ${activeItem === ItemsEnum.Multiselect && "sidebar-item-active"}`}
          onClick={() => setActiveItem(ItemsEnum.Multiselect)}
        >
          Multiselect
        </p>
      </div>
    </div>
  );
};
