// vue-docs/src/xui/Select/SelectOption.vue
<template>
  <option
    :class="['select-option', { selected: isSelected }]"
    @click="handleClick"
  >
    <slot></slot>
  </option>
</template>

<script setup>
import { defineProps, withDefaults } from "vue";

const props = defineProps({
  selected: Boolean,
  onClick: Function,
});

const isSelected = props.selected;

const handleClick = () => {
  props.onClick?.();
};
</script>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components-svelte/src/select/SelectOption.svelte
<script lang="ts">
import "./styles.css"

export let selected: boolean = false
export let onClick: () => void = () => {}
</script>

<div
    class="select-option {selected ? 'selected' : ''}"
    on:click={onClick}
    on:keydown={event => event.key === 'Enter' || event.key === 'Space' && onClick()}
    tabindex="0"
    role="button"
>
    <slot></slot>
</div>
