// vue-docs/src/xui/Multiselect/MultiselectItem.vue
<script setup>
import { defineProps, defineEmits } from "vue";

const props = defineProps({
  onClick: Function,
});

const emits = defineEmits(["click"]);

const handleClick = () => {
  props.onClick();
};
</script>

<template>
  <section class="multiselect-input-item">
    <slot></slot>
    <button class="multiselect-input-item-x-btn" @click="handleClick">
      <font-awesome-icon class="accordion-icon" icon="times" />
    </button>
  </section>
</template>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components-svelte/src/multiselect/MultiselectItem.svelte
<script lang="ts">
export let onClick: () => void;

function handleClick() {
    onClick();
}
</script>

<section class="multiselect-input-item" {...$$props}>
    <slot></slot>
    <button class="multiselect-input-item-x-btn" on:click={handleClick}>
        <svg class="multiselect-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512">
            <!-- !Font Awesome Free  -->
            <path fill="currentColor" d="M342.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L192 210.7 86.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L146.7 256 41.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L192 301.3 297.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L237.3 256 342.6 150.6z"/>
        </svg>
    </button>
</section>
