// vue-docs/src/xui/Multiselect/MultiselectOption.vue
<template>
  <div
    :class="['multiselect-option', { disabled: disabled, selected: selected }]"
    @click="handleClick"
    v-if="!disabled"
  >
    <slot></slot>
  </div>
</template>

<script setup>
import { defineProps, defineEmits } from "vue";

const props = defineProps({
  disabled: Boolean,
  selected: Boolean,
});

const emits = defineEmits(["click"]);

const handleClick = () => {
  if (!props.disabled) {
    emits("click");
  }
};
</script>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components-svelte/src/multiselect/MultiselectOption.svelte
<script lang="ts">

export let disabled: boolean = false;
export let selected: boolean = false;
export let onClick: () => void;

function handleClick() {
    if (!disabled) {
        onClick()
    }
}
</script>

{#if !disabled}
    <div 
        class="multiselect-option"
        class:selected={selected} 
        class:disabled={disabled} 
        role="button"
        tabindex="0"
        on:keydown={event => event.key === 'Enter' || event.key === 'Space' && handleClick()}
        on:click={handleClick}
        {...$$props}
    >
        <slot></slot>
    </div>
{/if}
