// vue-docs/src/views/ComposableMenu.vue
<template>
  <Example :codeContent="exampleCode">
    <template v-slot:exampleContent>
      <div class="center">
        <Menu>
          <MenuButton :onMenuButtonClick="toggleMenu">
            <template v-slot:default> Click me to open menu </template>
          </MenuButton>

          <MenuDropdown :open="isOpen">
            <MenuItem
              :item="{ id: '1', value: 'Action 1' }"
              @click="handleItemClick"
            >
              First Action
            </MenuItem>
            <MenuItem
              :item="{ id: '2', value: 'Action 2' }"
              @click="handleItemClick"
            >
              Second Action
            </MenuItem>
          </MenuDropdown>
        </Menu>
      </div>
    </template>
  </Example>
</template>

<script setup>
import { ref } from "vue";
import Example from "../components/Example.vue";
import Menu from "../xui/Menu/Menu.vue";
import MenuButton from "../xui/Menu/MenuButton.vue";
import MenuItem from "../xui/Menu/MenuItem.vue";
import MenuDropdown from "../xui/Menu/MenuDropdown.vue";

const isOpen = ref(false);
const selectedItem = ref(null);

const toggleMenu = () => {
  isOpen.value = !isOpen.value;
};

const handleItemClick = (item) => {
  window.alert("item was clicked: " + item.value);
};

const exampleCode = `
<div class="center">
    <Menu>
        <MenuButton :onMenuButtonClick="toggleMenu">
        <template v-slot:default> Click me to open menu </template>
        </MenuButton>

        <MenuDropdown :open="isOpen">
        <MenuItem
            :item="{ id: '1', value: 'Action 1' }"
            @click="handleItemClick"
        >
            First Action
        </MenuItem>
        <MenuItem
            :item="{ id: '2', value: 'Action 2' }"
            @click="handleItemClick"
        >
            Second Action
        </MenuItem>
        </MenuDropdown>
    </Menu>
</div>
`;
</script>

// svelte-docs/src/routes/menu/ComposableMenu.svelte
<script lang="ts">
  import { Menu, MenuButton, MenuDropdown, MenuItem } from 'x-ui-components-svelte'
  import type { Item } from '../../xui/menu/types';
  
    let isOpen = false;
  
    function toggleOpen() {
      isOpen = !isOpen;
    }
  
    function handleItemClick(item: Item) {
      isOpen = false; // Close the dropdown on item click
      window.alert('Item clicked ' + item.value)
    }
  </script>
  
  <div class="center">
    <Menu>
      <MenuButton onMenuButtonClick={toggleOpen}>
        Composable
      </MenuButton>
      <MenuDropdown open={isOpen}>
        <MenuItem 
          onClick={handleItemClick}
          item={{ id: "1", value: "Action 1" }}
        >
          First Action
        </MenuItem>
      </MenuDropdown>
    </Menu>
  </div>
  
  <style>
    .center {
      display: flex;
      justify-content: center;
      align-items: center;
    }
  </style>
