// libs/x-ui-components-vue/src/Modal/Modal.vue
<script setup>
import { ref, watch, onMounted, onUnmounted } from "vue";

const props = defineProps({
  title: String,
  isOpen: Boolean,
  onClose: Function,
  component: Boolean,
  isStatic: Boolean,
});
const open = ref(props.isOpen ?? false);

watch(
  () => props.isOpen,
  (newValue) => {
    if (newValue !== undefined) open.value = newValue;
  }
);

const close = () => {
  if (!props.isStatic) {
    open.value = false;
  }
  props.onClose?.();
};

const handleKeyDown = (event) => {
  if (event.key === "Escape" && !props.isStatic && props.component) close(); // ESC key
};

const handleClickOutside = (event) => {
  if (
    event.target.id === "modal-backdrop" &&
    !props.isStatic &&
    props.component
  )
    close();
};

onMounted(() => {
  document.addEventListener("keydown", handleKeyDown);
});
onUnmounted(() => {
  document.removeEventListener("keydown", handleKeyDown);
  document.removeEventListener("mousedown", handleClickOutside);
});
</script>

<template>
  <Teleport to="body" v-if="open">
    <div
      id="modal-backdrop"
      class="modal-backdrop"
      @mousedown="handleClickOutside"
    >
      <div v-if="component" class="modal-content" @click.stop>
        <div class="modal-title">{{ title }}</div>
        <slot></slot>
        <div class="modal-footer">
          <button class="modal-button" @click="close">OK</button>
        </div>
      </div>
      <template v-else>
        <slot></slot>
      </template>
    </div>
  </Teleport>
</template>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components-react/src/Modal/Modal.tsx
import React, { useEffect, useState } from "react";
import ReactDOM from "react-dom";
import "./styles.css";

export interface ReactChildren {
  children: React.ReactNode;
}
export interface ModalProps extends ReactChildren {
  isOpen?: boolean;
  onClose?: () => void;
  component?: boolean;
  isStatic?: boolean;
  title?: string;
}
export interface ButtonProps extends ReactChildren {
  onClick: () => void;
}

Modal.Content = ({ children, ...props }: ReactChildren) => {
  // todo: is this stopPropagation needed?
  return (
    <div
      className="modal-content"
      onClick={(e) => e.stopPropagation()}
      {...props}
    >
      {children}
    </div>
  );
};
Modal.Title = ({ children, ...props }: ReactChildren) => {
  return (
    <div className="modal-title" {...props}>
      {children}
    </div>
  );
};
Modal.Button = ({
  children,
  onClick: onButtonClick,
  ...props
}: ButtonProps) => {
  return (
    <button className="modal-button" onClick={() => onButtonClick()} {...props}>
      {children}
    </button>
  );
};

export function Modal({
  isOpen,
  onClose,
  title,
  children,
  component,
  isStatic,
  ...props
}: ModalProps) {
  const [open, setOpen] = useState<boolean>(isOpen ?? false);

  useEffect(() => {
    isOpen !== undefined && setOpen(isOpen);
  }, [isOpen]);

  const close = () => {
    !isStatic && setOpen(false);
    onClose?.();
  };

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.keyCode === 27) close(); // ESC key
    };

    const handleClickOutside = (event: MouseEvent) => {
      if ((event.target as HTMLElement).id === "modal-backdrop") close();
    };

    if (open && !isStatic) {
      document.addEventListener("keydown", handleKeyDown);
      document.addEventListener("mousedown", handleClickOutside);
    }

    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("mousedown", handleClickOutside);
    };
  }, [open, onClose]);

  if (!open) return null;

  return ReactDOM.createPortal(
    <div id="modal-backdrop" className="modal-backdrop" {...props}>
      {component ? (
        <Modal.Content>
          <Modal.Title>{title}</Modal.Title>
          {children}
          <div className="modal-footer">
            <Modal.Button onClick={close}>OK</Modal.Button>
          </div>
        </Modal.Content>
      ) : (
        children
      )}
    </div>,
    document.body
  );
}
