// libs/x-ui-components-vue/src/Select/SelectInput.vue
<script setup>
import { defineProps, computed, watch } from "vue";

const props = defineProps({
  value: Object,
  onClick: Function,
  disabled: Boolean,
});

const handleClick = () => {
  props.onClick?.();
};

const displayValue = computed(() => props?.value?.value ?? "");
</script>

<template>
  <div class="select-input-wrapper">
    <input
      class="select-input"
      type="text"
      :value="displayValue"
      @input="() => {}"
      @click="handleClick"
      :disabled="disabled"
      readonly
    />
  </div>
</template>

<style scoped>
@import "./styles.css";
</style>

// svelte-docs/src/xui/select/SelectInput.svelte
<script lang="ts">
import "./styles.css"
import type {Option} from './types'

export let value: Option | undefined;
export let disabled: boolean = false;
export let onClick: () => void = () => {};

</script>

<div class="select-input-wrapper">
    <input
        class="select-input"
        type="text"
        value={value?.value ?? ""}
        on:click={onClick}
        disabled={disabled}
        readonly
    />
</div>
