// vue-docs/src/xui/Multiselect/Multiselect.vue
<script setup>
import { ref, watch, onMounted, onUnmounted, computed } from "vue";

const props = defineProps({
  options: Array,
  defaultValue: Array,
  value: Array,
  open: Boolean,
  disabled: Boolean,
  onChange: Function,
  onInputClick: Function,
  isStatic: Boolean,
  enableSearch: Boolean,
  clearAll: Boolean,
  maxSelectedItems: Number,
  component: Boolean,
});

const searchValue = ref("");
const dropdownRef = ref(null);
const initialValue = props.options?.filter((option) =>
  props.defaultValue?.includes(option.id)
);
const value = ref(initialValue);
const areOptionsVisible = ref(props.open || false);

const visibleOptions = computed(() => {
  return props.enableSearch && searchValue.value
    ? props.options.filter((option) =>
        option.value.toLowerCase().includes(searchValue.value.toLowerCase())
      )
    : props.options;
});

const maxSelectionReached = computed(
  () => props.maxSelectedItems && value.value.length >= props.maxSelectedItems
);

watch(
  () => props.open,
  (newVal) => {
    if (newVal !== undefined) areOptionsVisible.value = newVal;
  }
);

onMounted(() => {
  const handleClickOutside = (event) => {
    if (
      !props.isStatic &&
      dropdownRef.value &&
      !dropdownRef.value.contains(event.target)
    ) {
      areOptionsVisible.value = false;
    }
  };
  const handleKeyDown = (event) => {
    if (!props.isStatic && event.key === "Escape")
      areOptionsVisible.value = false;
  };
  document.addEventListener("mousedown", handleClickOutside);
  document.addEventListener("keydown", handleKeyDown);
  onUnmounted(() => {
    document.removeEventListener("mousedown", handleClickOutside);
    document.removeEventListener("keydown", handleKeyDown);
  });
});

const onOptionClick = (option) => {
  if (maxSelectionReached.value && !value.value.find((v) => v.id === option.id))
    return;
  const alreadySelected = value.value.find((v) => v.id === option.id);
  value.value = alreadySelected
    ? value.value.filter((v) => v.id !== option.id)
    : [...value.value, option];
  areOptionsVisible.value = false;
  searchValue.value = "";
  props.onChange?.(value.value, option);
};

const unselectOption = (option) => {
  value.value = value.value.filter((v) => v.id !== option.id);
};

const onSearch = (event) => {
  areOptionsVisible.value = true;
  searchValue.value = event.target.value;
};

const clearAllSelectedOptions = (event) => {
  event.stopPropagation();
  value.value = [];
};

const handleInputClick = () => {
  if (!props.disabled && !props.isStatic) {
    areOptionsVisible.value = !areOptionsVisible.value;
  }
  props.onInputClick?.();
};

const isSelected = (option) => {
  return value.value.some((v) => v.id === option.id);
};
</script>

<template>
  <div class="multiselect-wrapper">
    <div
      v-if="component"
      class="multiselect-input-wrapper"
      :class="{ 'clear-all-enabled': clearAll }"
    >
      <section
        class="multiselect-input-section"
        :class="{ 'clear-all-enabled': clearAll }"
        @click="handleInputClick"
      >
        <section class="multiselect-input-items">
          <div v-for="v in value" :key="v.id" class="multiselect-input-item">
            {{ v.value }}
            <button
              class="multiselect-input-item-x-btn"
              @click="unselectOption(v)"
            >
              <font-awesome-icon class="accordion-icon" icon="times" />
            </button>
          </div>
        </section>
        <input
          v-if="enableSearch"
          :size="searchValue.length > 0 ? searchValue.length : 1"
          class="multiselect-input"
          type="text"
          v-model="searchValue"
          @input="onSearch"
        />
        <button
          v-if="clearAll"
          class="multiselect-input-item-x-btn clear-all-enabled"
          @click="clearAllSelectedOptions"
        >
          <font-awesome-icon icon="circle-xmark" />
        </button>
      </section>
    </div>
    <div
      v-if="areOptionsVisible"
      class="multiselect-dropdown"
      ref="dropdownRef"
    >
      <div
        v-for="option in visibleOptions"
        :key="option.id"
        :class="[
          'multiselect-option',
          { disabled: maxSelectionReached, selected: isSelected(option) },
        ]"
        @click="onOptionClick(option)"
      >
        {{ option.value }}
      </div>
    </div>
    <slot v-else></slot>
  </div>
</template>

<style scoped>
@import "./styles.css";
</style>

// libs/x-ui-components/src/Multiselect/Multiselect.tsx
import React, { Children, useEffect, useRef, useState } from "react";
import "./styles.css";
import { MdClose } from "react-icons/md";
import { IoCloseCircle } from "react-icons/io5";

export interface ReactChildren {
  children?: React.ReactNode;
}
export interface Option {
  id: string | number;
  value: string;
}
export interface MultiselectProps extends ReactChildren {
  options?: Option[];
  open?: boolean;
  disabled?: boolean;
  value?: Option[];
  defaultValue?: string[] | number[];
  onChange?: (value: Option[], newlyAdded: Option) => void;
  onInputClick?: () => void;
  isStatic?: boolean;
  enableSearch?: boolean;
  onSearch?: (value: string) => boolean;
  clearAll?: boolean;
  maxSelectedItems?: number;
  component?: boolean;
}

export interface MultiselectInputProps extends ReactChildren {
  areOptionsVisible: boolean;
  onInputClick: () => void;
  onClearAllClick?: () => void;
  enableSearch?: boolean;
  onSearch?: (value: string) => boolean;
  clearAll?: boolean;
  disabled?: boolean;
  searchValue?: string;
}

Multiselect.Input = ({
  clearAll,
  disabled,
  onInputClick,
  enableSearch,
  onSearch,
  searchValue,
  children,
  onClearAllClick,
}: MultiselectInputProps) => {
  return (
    <div
      className={`multiselect-input-wrapper ${clearAll && "clear-all-enabled"}`}
    >
      <section
        className={`multiselect-input-section ${
          clearAll && "clear-all-enabled"
        }`}
        onClick={() => {
          !disabled && onInputClick?.();
        }}
      >
        <section className="multiselect-input-items">{children}</section>
        {enableSearch && (
          <input
            size={
              searchValue && searchValue?.length > 0 ? searchValue.length : 1
            }
            className="multiselect-input"
            type="text"
            value={searchValue}
            onChange={(e) => onSearch?.(e.target.value)}
          />
        )}
        {clearAll && (
          <button className="multiselect-input-item-x-btn clear-all-enabled">
            <IoCloseCircle onClick={onClearAllClick} />
          </button>
        )}
      </section>
    </div>
  );
};

export interface MultiselectItemProps extends ReactChildren {
  onClick: () => void;
}
Multiselect.Item = ({ onClick, children }: MultiselectItemProps) => {
  return (
    <section className="multiselect-input-item">
      {children}
      <button className="multiselect-input-item-x-btn" onClick={onClick}>
        <MdClose />
      </button>
    </section>
  );
};

export interface MultiselectDropdownProps extends ReactChildren {
  areOptionsVisible: boolean;
}
Multiselect.Dropdown = ({
  areOptionsVisible,
  children,
}: MultiselectDropdownProps) => {
  if (areOptionsVisible) {
    return <div className="multiselect-dropdown">{children}</div>;
  }

  return <></>;
};

export interface MultiselectOptionProps extends ReactChildren {
  disabled?: boolean;
  selected?: boolean;
  onClick: () => void;
}
Multiselect.Option = ({
  disabled,
  selected,
  onClick,
  children,
}: MultiselectOptionProps) => {
  return (
    <option
      className={`${disabled ? "disabled" : ""} multiselect-option ${
        selected ? "selected" : ""
      }`}
      onClick={() => onClick()}
    >
      {children}
    </option>
  );
};

export function Multiselect({
  options = [],
  defaultValue,
  open,
  disabled,
  onChange,
  onInputClick,
  isStatic,
  value: valueProp,
  enableSearch,
  clearAll,
  maxSelectedItems,
  component,
  children,
}: MultiselectProps) {
  const [searchValue, setSearchValue] = useState("");
  const initialValue = options.filter((option) =>
    defaultValue != undefined
      ? // @ts-ignore
        defaultValue.includes(option.id)
      : false
  );
  const [value, setValue] = useState<Option[]>(initialValue);
  const [areOptionsVisible, setAreOptionsVisible] = useState(open ?? false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const maxSelectionReached =
    maxSelectedItems && value?.length >= maxSelectedItems;

  useEffect(() => {
    open !== undefined && setAreOptionsVisible(open);
  }, [open]);

  useEffect(() => {
    valueProp !== undefined && setValue(valueProp);
  }, [valueProp]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        !isStatic &&
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setAreOptionsVisible(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (!isStatic && event.keyCode === 27) setAreOptionsVisible(false); // ESC key
    };

    // Add when the component mounts
    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleKeyDown);

    // Return function to be called when unmounted
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  const onOptionClick = (option: Option) => {
    const alreadySelected = value.find((val) => val.id === option.id);
    const newValue =
      alreadySelected === undefined
        ? [...value, option]
        : value.filter((val) => val.id !== alreadySelected.id);

    if (!maxSelectionReached || (alreadySelected && maxSelectionReached)) {
      if (!isStatic) {
        setValue(newValue);
        setAreOptionsVisible(false);
      }
      setSearchValue("");
      onChange?.(newValue, option);
    }
  };

  const unselectOption = (option: Option) => {
    const newValue = value.filter((val) => val.id !== option.id);
    setValue(newValue);
  };

  const onSearch = (searchValue: string) => {
    setAreOptionsVisible(true);
    setSearchValue(searchValue);
  };

  const clearAllSelectedOptions = (e: any) => {
    e.stopPropagation();
    setValue([]);
  };

  const visibleOptions =
    enableSearch && searchValue !== undefined && searchValue !== ""
      ? options?.filter((option) =>
          option.value.toLowerCase().includes(searchValue.toLowerCase())
        )
      : options;

  return (
    <div className="multiselect-wrapper">
      {component ? (
        <>
          <div
            className={`multiselect-input-wrapper ${
              clearAll && "clear-all-enabled"
            }`}
          >
            <section
              className={`multiselect-input-section ${
                clearAll && "clear-all-enabled"
              }`}
              onClick={() => {
                !disabled &&
                  !isStatic &&
                  setAreOptionsVisible(!areOptionsVisible);
                !disabled && onInputClick?.();
              }}
            >
              <section className="multiselect-input-items">
                {value.map((v) => (
                  <section className="multiselect-input-item">
                    {v.value}
                    <button
                      className="multiselect-input-item-x-btn"
                      onClick={() => !disabled && unselectOption(v)}
                    >
                      <MdClose />
                    </button>
                  </section>
                ))}
              </section>
              {enableSearch && (
                <input
                  size={searchValue?.length > 0 ? searchValue.length : 1}
                  className="multiselect-input"
                  type="text"
                  value={searchValue}
                  onChange={(e) => onSearch(e.target.value)}
                />
              )}
              {clearAll && (
                <button className="multiselect-input-item-x-btn clear-all-enabled">
                  <IoCloseCircle onClick={clearAllSelectedOptions} />
                </button>
              )}
            </section>
          </div>
          {areOptionsVisible && (
            <div ref={dropdownRef} className="multiselect-dropdown">
              {visibleOptions.map((option) => (
                <option
                  key={option.id}
                  className={`${
                    maxSelectionReached ? "disabled" : ""
                  } multiselect-option ${
                    value.find((val) => val.id === option.id) !== undefined
                      ? "selected"
                      : ""
                  }`}
                  onClick={() => onOptionClick(option)}
                >
                  {option.value}
                </option>
              ))}
            </div>
          )}
        </>
      ) : (
        children
      )}
    </div>
  );
}
