// vue-docs/src/components/CodeBlock.vue
<script setup>
import "prismjs";
import "prismjs/components/prism-jsx.min"; // Ensure JSX syntax is supported
import Prism from "vue-prism-component";
import "prismjs/themes/prism-twilight.css";

defineProps(["code"]);
</script>

<template>
  <prism language="jsx" :code="code">{{ code }}</prism>
</template>

// svelte-docs/src/components/CodeBlock.svelte
<script lang="ts">
import Prism from 'prismjs';
import 'prismjs/themes/prism-tomorrow.css'; // or any other theme you prefer
import 'prismjs/components/prism-javascript.js';

export let code: string;

const language = "js"
</script>

<pre><code class="language-js">{@html Prism.highlight(code, Prism.languages[language], language)}</code></pre>
