// vue-docs/src/components/ComponentApiTable.vue
<script setup>
defineProps(["values"]);
</script>

<template>
  <div class="table-component">
    <table>
      <thead>
        <tr>
          <th>Prop</th>
          <th>Description</th>
          <th>Type</th>
          <th>Default</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="value in values">
          <td className="prop">{{ value.prop }}</td>
          <td className="description">{{ value.description }}</td>
          <td>
            <code>{{ value.type }}</code>
          </td>
          <td>
            <code>{{ value.default }}</code>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// svelte-docs/src/components/ComponentApiTable.svelte
<script lang="ts">
import '../shared.css'
import type { ComponentApiDefinition } from "./types";

export let values: ComponentApiDefinition[] = [];
</script>
    
<div class="table-component">
    <table>
        <thead>
        <tr>
            <th>Prop</th>
            <th>Description</th>
            <th>Type</th>
            <th>Default</th>
        </tr>
        </thead>
        <tbody>
            {#each values as value}
                <tr>
                    <td class="prop">{value.prop}</td>
                    <td class="description">{value.description}</td>
                    <td>
                    <code>{value.type}</code>
                    </td>
                    <td>
                    <code>{value.default}</code>
                    </td>
                </tr>
            {/each}
        </tbody>
    </table>
</div>
