// vue-docs/src/components/Example.vue
<template>
  <div class="example-box">
    <div class="example-box-buttons" style="margin-bottom: 10px">
      <button class="btn-switch" @click="setViewMode('example')">
        Example
      </button>
      <button class="btn-switch" @click="setViewMode('code')">Code</button>
    </div>
    <div style="display: flex; flex-direction: column">
      <template v-if="viewMode === 'example'">
        <slot name="exampleContent">{{ exampleContent }}</slot>
      </template>
      <template v-else>
        <CodeBlock :code="codeContent"></CodeBlock>
      </template>
    </div>
  </div>
</template>

<script setup>
import CodeBlock from "./CodeBlock.vue";
import { ref } from "vue";

defineProps(["codeContent", "exampleContent"]);

const viewMode = ref("example");

function setViewMode(v) {
  viewMode.value = v;
}
</script>

<style>
/* Add your CSS for .btn-switch and other elements here */
</style>

// svelte-docs/src/components/Example.svelte
<script lang="ts">
import CodeBlock from './CodeBlock.svelte';

export let codeContent: string;
let viewMode = 'example'; // Start showing the example by default
</script>

<div class="example-box">
<div class="example-box-buttons" style="margin-bottom: 10px;">
    <button class="btn-switch" on:click={() => viewMode = 'example'}>
    Example
    </button>
    <button class="btn-switch" on:click={() => viewMode = 'code'}>
    Code
    </button>
</div>
<div style="display: flex; flex-direction: column;">
    {#if viewMode === 'example'}
    <slot name="exampleContent" />
    {:else}
    <CodeBlock code={codeContent} />
    {/if}
</div>
</div>

<style>
.example-box-buttons {
    margin-bottom: 10px;
}
</style>
