// react-docs/src/components/Example.tsx
import { useState } from "react";
import CodeBlock from "./CodeBlock";

interface ExampleProps {
  exampleContent: React.ReactNode;
  codeContent: React.ReactNode;
}

const Example = ({ exampleContent, codeContent }: ExampleProps) => {
  const [viewMode, setViewMode] = useState("example");

  return (
    <div className="example-box">
      <div className="example-box-buttons" style={{ marginBottom: "10px" }}>
        <button className="btn-switch" onClick={() => setViewMode("example")}>
          Example
        </button>
        <button className="btn-switch" onClick={() => setViewMode("code")}>
          Code
        </button>
      </div>
      <div style={{ display: "flex", flexDirection: "column" }}>
        {viewMode === "example" ? (
          exampleContent
        ) : (
          <CodeBlock code={codeContent as string}></CodeBlock>
        )}
      </div>
    </div>
  );
};

export default Example;

// svelte-docs/src/components/Example.svelte
<script lang="ts">
import CodeBlock from './CodeBlock.svelte';

export let codeContent: string;
let viewMode = 'example'; // Start showing the example by default
</script>

<div class="example-box">
<div class="example-box-buttons" style="margin-bottom: 10px;">
    <button class="btn-switch" on:click={() => viewMode = 'example'}>
    Example
    </button>
    <button class="btn-switch" on:click={() => viewMode = 'code'}>
    Code
    </button>
</div>
<div style="display: flex; flex-direction: column;">
    {#if viewMode === 'example'}
    <slot name="exampleContent" />
    {:else}
    <CodeBlock code={codeContent} />
    {/if}
</div>
</div>

<style>
.example-box-buttons {
    margin-bottom: 10px;
}
</style>
