// libs/x-ui-components-vue/src/Menu/MenuItem.vue
<script setup>
import { defineProps, withModifiers } from "vue";

const props = defineProps({
  item: Object,
  isDisabled: {
    type: Boolean,
    default: false,
  },
});

const emit = defineEmits(["click"]);

function handleClick() {
  if (!props.isDisabled) {
    emit("click", props.item);
  }
}
</script>

<template>
  <div
    :key="item.id"
    :class="['menu-option', { disabled: isDisabled }]"
    @click="handleClick"
  >
    <slot></slot>
  </div>
</template>

<style scoped>
@import "./styles.css";
</style>

// svelte-docs/src/xui/menu/MenuItem.svelte
<script lang="ts">
import "./styles.css"
  import type { Item } from "./types";

export let item: Item;
export let isDisabled: boolean = false; // Default to false if not provided
export let onClick: (item: Item) => void;

function handleClick() {
    if (!isDisabled) {
        onClick(item);
    }
}
</script>

<div
    class="menu-option {isDisabled ? 'disabled' : ''}"
    on:click={handleClick}
    >
    <slot></slot>
</div>
