// vue-docs/src/xui/Multiselect/Multiselect.vue
<template>
  <div class="multiselect-wrapper">
    <div
      v-if="component"
      class="multiselect-input-wrapper"
      :class="{ 'clear-all-enabled': clearAll }"
    >
      <section
        class="multiselect-input-section"
        :class="{ 'clear-all-enabled': clearAll }"
        @click="handleInputClick"
      >
        <section class="multiselect-input-items">
          <div v-for="v in value" :key="v.id" class="multiselect-input-item">
            {{ v.value }}
            <button
              class="multiselect-input-item-x-btn"
              @click="unselectOption(v)"
            >
              <font-awesome-icon class="accordion-icon" icon="times" />
            </button>
          </div>
        </section>
        <input
          v-if="enableSearch"
          :size="searchValue.length > 0 ? searchValue.length : 1"
          class="multiselect-input"
          type="text"
          v-model="searchValue"
          @input="onSearch"
        />
        <button
          v-if="clearAll"
          class="multiselect-input-item-x-btn clear-all-enabled"
        >
          <font-awesome-icon icon="circle-xmark" />
        </button>
      </section>
    </div>
    <div
      v-if="areOptionsVisible"
      class="multiselect-dropdown"
      ref="dropdownRef"
    >
      <div
        v-for="option in visibleOptions"
        :key="option.id"
        :class="[
          'multiselect-option',
          { disabled: maxSelectionReached, selected: isSelected(option) },
        ]"
        @click="onOptionClick(option)"
      >
        {{ option.value }}
      </div>
    </div>
    <slot v-else></slot>
  </div>
</template>

<script setup>
import { ref, watch, onMounted, onUnmounted, computed } from "vue";

const props = defineProps({
  options: Array,
  defaultValue: Array,
  value: Array,
  open: Boolean,
  disabled: Boolean,
  onChange: Function,
  onInputClick: Function,
  isStatic: Boolean,
  enableSearch: Boolean,
  clearAll: Boolean,
  maxSelectedItems: Number,
  component: Boolean,
});

const searchValue = ref("");
const value = ref(props.defaultValue || []);
const areOptionsVisible = ref(props.open || false);

const visibleOptions = computed(() => {
  return props.enableSearch && searchValue.value
    ? props.options.filter((option) =>
        option.value.toLowerCase().includes(searchValue.value.toLowerCase())
      )
    : props.options;
});

const maxSelectionReached = computed(
  () => props.maxSelectedItems && value.value.length >= props.maxSelectedItems
);

watch(
  () => props.open,
  (newVal) => {
    if (newVal !== undefined) areOptionsVisible.value = newVal;
  }
);

// onMounted(() => {
//   const handleClickOutside = (event) => {
//     if (
//       !props.isStatic &&
//       dropdownRef.value &&
//       !dropdownRef.value.contains(event.target)
//     ) {
//       areOptionsVisible.value = false;
//     }
//   };
//   const handleKeyDown = (event) => {
//     if (!props.isStatic && event.key === "Escape")
//       areOptionsVisible.value = false;
//   };
//   document.addEventListener("mousedown", handleClickOutside);
//   document.addEventListener("keydown", handleKeyDown);
//   onUnmounted(() => {
//     document.removeEventListener("mousedown", handleClickOutside);
//     document.removeEventListener("keydown", handleKeyDown);
//   });
// });

const onOptionClick = (option) => {
  if (maxSelectionReached.value && !value.value.find((v) => v.id === option.id))
    return;
  const alreadySelected = value.value.find((v) => v.id === option.id);
  value.value = alreadySelected
    ? value.value.filter((v) => v.id !== option.id)
    : [...value.value, option];
  areOptionsVisible.value = false;
  searchValue.value = "";
  props.onChange?.(value.value, option);
};

const unselectOption = (option) => {
  value.value = value.value.filter((v) => v.id !== option.id);
};

const onSearch = (event) => {
  areOptionsVisible.value = true;
  searchValue.value = event.target.value;
};

const clearAllSelectedOptions = (event) => {
  event.stopPropagation();
  value.value = [];
};

const handleInputClick = () => {
  if (!props.disabled && !props.isStatic) {
    areOptionsVisible.value = !areOptionsVisible.value;
  }
  props.onInputClick?.();
};

const isSelected = (option) => {
  return value.value.some((v) => v.id === option.id);
};
</script>

<style scoped>
@import "./styles.css";
</style>

// react-docs/src/xui/Multiselect/Multiselect.tsx
import { useEffect, useRef, useState } from "react";
import "./styles.css";
import { MdClose } from "react-icons/md";
import { IoCloseCircle } from "react-icons/io5";

interface Option {
  id: string | number;
  value: string;
}
interface MultiselectProps {
  options: Option[];
  open?: boolean;
  disabled?: boolean;
  value?: Option[];
  defaultValue?: Option[];
  onChange?: (value: Option[], newlyAdded: Option) => void;
  onInputClick?: () => void;
  isStatic?: boolean;
  enableSearch?: boolean;
  onSearch?: (value: string) => boolean;
  clearAll?: boolean;
  maxSelectedItems?: number;
}

export function Multiselect({
  options,
  defaultValue,
  open,
  disabled,
  onChange,
  onInputClick,
  isStatic,
  value: valueProp,
  enableSearch,
  clearAll,
  maxSelectedItems,
}: MultiselectProps) {
  const [searchValue, setSearchValue] = useState("");
  const [value, setValue] = useState<Option[]>(defaultValue ?? []);
  const [areOptionsVisible, setAreOptionsVisible] = useState(open ?? false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const maxSelectionReached =
    maxSelectedItems && value?.length >= maxSelectedItems;

  useEffect(() => {
    open !== undefined && setAreOptionsVisible(open);
  }, [open]);

  useEffect(() => {
    valueProp !== undefined && setValue(valueProp);
  }, [valueProp]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        !isStatic &&
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node)
      ) {
        setAreOptionsVisible(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (!isStatic && event.keyCode === 27) setAreOptionsVisible(false); // ESC key
    };

    // Add when the component mounts
    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("keydown", handleKeyDown);

    // Return function to be called when unmounted
    return () => {
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, []);

  const onOptionClick = (option: Option) => {
    const alreadySelected = value.find((val) => val.id === option.id);
    const newValue =
      alreadySelected === undefined
        ? [...value, option]
        : value.filter((val) => val.id !== alreadySelected.id);

    if (!maxSelectionReached || (alreadySelected && maxSelectionReached)) {
      if (!isStatic) {
        setValue(newValue);
        setAreOptionsVisible(false);
      }
      setSearchValue("");
      onChange?.(newValue, option);
    }
  };

  const unselectOption = (option: Option) => {
    const newValue = value.filter((val) => val.id !== option.id);
    setValue(newValue);
  };

  const onSearch = (searchValue: string) => {
    setAreOptionsVisible(true);
    setSearchValue(searchValue);
  };

  const clearAllSelectedOptions = (e: any) => {
    e.stopPropagation();
    setValue([]);
  };

  const visibleOptions =
    enableSearch && searchValue !== undefined && searchValue !== ""
      ? options?.filter((option) =>
          option.value.toLowerCase().includes(searchValue.toLowerCase())
        )
      : options;

  return (
    <div className="multiselect-wrapper">
      <div
        className={`multiselect-input-wrapper ${
          clearAll && "clear-all-enabled"
        }`}
      >
        <section
          className={`multiselect-input-section ${
            clearAll && "clear-all-enabled"
          }`}
          onClick={() => {
            !disabled && !isStatic && setAreOptionsVisible(!areOptionsVisible);
            !disabled && onInputClick?.();
          }}
        >
          <section className="multiselect-input-items">
            {value.map((v) => (
              <section className="multiselect-input-item">
                {v.value}
                <button
                  className="multiselect-input-item-x-btn"
                  onClick={() => !disabled && unselectOption(v)}
                >
                  <MdClose />
                </button>
              </section>
            ))}
          </section>
          {enableSearch && (
            <input
              size={searchValue?.length > 0 ? searchValue.length : 1}
              className="multiselect-input"
              type="text"
              value={searchValue}
              onChange={(e) => onSearch(e.target.value)}
            />
          )}
          {clearAll && (
            <button className="multiselect-input-item-x-btn clear-all-enabled">
              <IoCloseCircle onClick={clearAllSelectedOptions} />
            </button>
          )}
        </section>
      </div>
      {areOptionsVisible && (
        <div ref={dropdownRef} className="multiselect-dropdown">
          {visibleOptions.map((option) => (
            <option
              key={option.id}
              className={`${
                maxSelectionReached ? "disabled" : ""
              } multiselect-option ${
                value.find((val) => val.id === option.id) !== undefined
                  ? "selected"
                  : ""
              }`}
              onClick={() => onOptionClick(option)}
            >
              {option.value}
            </option>
          ))}
        </div>
      )}
    </div>
  );
}
